provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}

# Manages the Datadog - AWS integration
# This resource is responsible for setting up the IAM role in your AWS account
# that Datadog will use to collect metrics, logs, and traces.
resource "datadog_integration_aws" "main" {
  account_id = data.aws_caller_identity.current.account_id
  role_name  = "DatadogIntegrationRole"
  # The external_id is a shared secret between your AWS account and Datadog 
  # to ensure that only Datadog can assume the IAM role.
  # It is a best practice to generate a unique external_id for each integration.
  # You can generate one with `openssl rand -hex 16`
  external_id = var.external_id 

  # Define which AWS services Datadog should monitor.
  # You can customize this list based on your needs.
  # For a full list of available services, refer to the Datadog documentation.
  filter_tags = ["env:production", "team:backend"]
  host_tags   = ["project:lti", "env:production"]
  account_specific_namespace_rules = {
    auto_scaling = false
    opsworks     = false
  }
  metrics_collection_enabled = true
  resource_collection_enabled = true
}

# Output the External ID generated by the datadog_integration_aws resource if you 
# are letting Datadog create a new external_id for you.
# If you provide your own external_id, this output will be the same.
output "datadog_aws_integration_external_id" {
  description = "External ID for the Datadog AWS integration. This is needed when configuring the trust relationship in the IAM role."
  value       = datadog_integration_aws.main.external_id
  sensitive = true
} 